spring:
  data:
    rest:
      basePath: /aol
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/resources/static/,classpath:/mobileapp/ # Locations of static resources.

  profiles:
    active: dev

server:
  port: 8080
  contextPath: /

rest:
  baseUrl: /api/rest

